# whole-arm base trajectory controller
move_until_touch_topic_controller:
  mode: TRAJECTORY
  type: rewd_controllers/MoveUntilTouchTopicController
  # Forque Sensor
  forcetorque_wrench_name: /forque/forqueSensor
  forcetorque_tare_name: /forque/bias_controller/trigger
  # FingerVision
  # forcetorque_wrench_name: /fingervision/fv_3_l/wrench
  # forcetorque_tare_name: /fingervision/fingerVisionTaring
  sensor_force_limit: 50
  sensor_torque_limit: 5
  joints: [j2n6s200_joint_1, j2n6s200_joint_2, j2n6s200_joint_3,
    j2n6s200_joint_4, j2n6s200_joint_5, j2n6s200_joint_6]
  control_type: velocity
  constraints:
    j2n6s200_joint_1:
      goal: 0.02
      trajectory: 7
    j2n6s200_joint_2:
      goal: 0.02
      trajectory: 7
    j2n6s200_joint_3:
      goal: 0.02
      trajectory: 7
    j2n6s200_joint_4:
      goal: 0.02
      trajectory: 7
    j2n6s200_joint_5:
      goal: 0.02
      trajectory: 7
    j2n6s200_joint_6:
      goal: 0.02
      trajectory: 7
  gains: # Required because we're controlling a velocity interface
    j2n6s200_joint_1: {p: 3,  d: 0, i: 0, i_clamp: 1}
    j2n6s200_joint_2: {p: 3,  d: 0, i: 0, i_clamp: 1}
    j2n6s200_joint_3: {p: 3,  d: 0, i: 0, i_clamp: 1}
    j2n6s200_joint_4: {p: 3,  d: 0, i: 0, i_clamp: 1}
    j2n6s200_joint_5: {p: 3,  d: 0, i: 0, i_clamp: 1}
    j2n6s200_joint_6: {p: 3,  d: 0, i: 0, i_clamp: 1}
  max_ft_delay: 100
