# whole-arm base trajectory controller
trajectory_controller:
  mode: TRAJECTORY
  type: velocity_controllers/JointTrajectoryController
  joints: [joint_1, joint_2, joint_3,
    joint_4, joint_5, joint_6, "joint_7"]
  constraints:
    stopped_velocity_tolerance: 1.0
    joint_1:
      goal: 0.1
      trajectory: 10.0
    joint_2:
      goal: 0.1
      trajectory: 10.0
    joint_3:
      goal: 0.1
      trajectory: 10.0
    joint_4:
      goal: 0.1
      trajectory: 10.0
    joint_5:
      goal: 0.1
      trajectory: 10.0
    joint_6:
      goal: 0.1
      trajectory: 10.0
    joint_7:
      goal: 0.1
      trajectory: 10.0
  gains: # Required because we're controlling a velocity interface
    joint_1: {p: 5,  d: 0, i: 0, i_clamp: 2}
    joint_2: {p: 5,  d: 0, i: 0, i_clamp: 2}
    joint_3: {p: 5,  d: 0, i: 0, i_clamp: 2}
    joint_4: {p: 5,  d: 0, i: 0, i_clamp: 2}
    joint_5: {p: 5,  d: 0, i: 0, i_clamp: 2}
    joint_6: {p: 5,  d: 0, i: 0, i_clamp: 2}
    joint_7: {p: 5,  d: 0, i: 0, i_clamp: 2}